// frontend/src/components/ModelResponseCard.tsx
import { useState } from "react";
import { Button, Modal, Space } from "antd";

import { isPendingResponse } from "../features/evaluation/evaluation";
import type { DisplayModelResponse, EvaluationScore, FeedbackToggleResult } from "../features/evaluation/types";
import { toAnswerPreview } from "../features/evaluation/content";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { CommentPanel } from "./CommentPanel";
import { formatScore, ScoreBar } from "./ScoreBar";

interface ModelResponseCardProps {
  response: DisplayModelResponse;
  elapsedSeconds: number;
  feedbackSubmitting: boolean;
  showComments?: boolean;
  onFeedback: (responseId: number, feedbackType: FeedbackToggleResult["feedbackType"]) => void;
}

const dimensionLabels: Array<{ key: keyof EvaluationScore; label: string; weight: string }> = [
  { key: "relevance", label: "相关性", weight: "30%" },
  { key: "completeness", label: "完整性", weight: "25%" },
  { key: "clarity", label: "清晰度", weight: "20%" },
  { key: "format", label: "格式", weight: "15%" },
  { key: "safety", label: "安全性", weight: "10%" }
];

export function ModelResponseCard({
  response,
  elapsedSeconds,
  feedbackSubmitting,
  showComments = false,
  onFeedback
}: ModelResponseCardProps) {
  const [detailVisible, setDetailVisible] = useState(false);

  if (isPendingResponse(response)) {
    return (
      <article className="response-card pending">
        <ResponseHeader modelName={response.modelName} statusLabel="等待模型响应" scoreText="..." failed={false} />
        <div className="pending-answer" aria-label="模型响应等待中">
          <span />
          <span />
          <span />
        </div>
        <dl className="metric-row">
          <Metric label="耗时" value={`${elapsedSeconds}s`} />
          <Metric label="输出" value="等待中" />
          <Metric label="成本" value="待估算" />
        </dl>
      </article>
    );
  }

  const score = normalizedScore(response.score);
  const feedback = response.feedback;
  const failed = response.status !== "success";

  return (
    <article className={`response-card${failed ? " failed" : ""}`}>
      <ResponseHeader
        modelName={response.modelName}
        statusLabel={failed ? "调用失败" : "调用成功"}
        scoreText={failed ? "失败" : formatScore(score.final)}
        failed={failed}
      />
      <p className="answer-preview">{toAnswerPreview(response.answer)}</p>
      <dl className="metric-row">
        <Metric label="耗时" value={`${response.latencyMs}ms`} />
        <Metric label="输出" value={String(response.outputTokens)} />
        <Metric label="成本" value={`${formatCost(response.estimatedCost)} ${response.currency}`} />
      </dl>
      <div className="score-bars">
        <ScoreBar label="相关性" value={score.relevance} />
        <ScoreBar label="完整性" value={score.completeness} />
        <ScoreBar label="清晰度" value={score.clarity} />
      </div>
      <footer className="card-actions">
        <Button
          className={feedback.liked ? "active" : ""}
          disabled={feedbackSubmitting}
          onClick={() => onFeedback(response.id, "like")}
        >
          点赞 {feedback.likeCount}
        </Button>
        <Button
          danger
          className={feedback.disliked ? "danger active" : "danger"}
          disabled={feedbackSubmitting}
          onClick={() => onFeedback(response.id, "dislike")}
        >
          点踩 {feedback.dislikeCount}
        </Button>
        <Button type="primary" ghost onClick={() => setDetailVisible(true)}>
          查看全文
        </Button>
      </footer>
      <Modal
        title={`${response.modelName} · 回答详情`}
        open={detailVisible}
        width="min(860px, 94vw)"
        footer={null}
        onCancel={() => setDetailVisible(false)}
      >
        <section className="response-detail-modal">
          <MarkdownRenderer content={response.answer} />
          <div className="score-detail-list">
            {dimensionLabels.map((dimension) => {
              const value = score[dimension.key];
              const details = score.details[dimension.key] || ["暂无命中项明细"];
              return (
                <article key={dimension.key} className="score-detail-item">
                  <header>
                    <span>{dimension.label}</span>
                    <Space size={8}>
                      <strong>{typeof value === "number" ? `${formatScore(value)} / 10` : "-"}</strong>
                      <em>权重 {dimension.weight}</em>
                    </Space>
                  </header>
                  <ul>
                    {details.map((detail) => (
                      <li key={detail}>{detail}</li>
                    ))}
                  </ul>
                </article>
              );
            })}
          </div>
          <article className="score-detail-item">
            <header>
              <span>用户反馈</span>
              <Space size={8}>
                <strong>{feedback.liked ? "已点赞" : feedback.disliked ? "已点踩" : "未反馈"}</strong>
                <em>权重 10%</em>
              </Space>
            </header>
            <p>
              点赞 {feedback.likeCount} 次，点踩 {feedback.dislikeCount} 次。
              {score.feedbackScore === null || score.feedbackScore === undefined
                ? "暂无点赞或点踩，最终分保持基础分不变。"
                : `最终分 = 基础分 ${formatScore(score.baseFinal)} x 90% + 反馈分 ${formatScore(score.feedbackScore)} x 10%。`}
            </p>
          </article>
          {score.judgeComment ? (
            <article className="score-detail-item">
              <header>
                <span>LLM 评审理由</span>
                <Space size={8}>
                  <strong>{formatScore(score.judgeFinal)} / 10</strong>
                  <em>权重 40%</em>
                </Space>
              </header>
              <p>{score.judgeComment}</p>
            </article>
          ) : null}
          {showComments ? <CommentPanel responseId={response.id} /> : null}
        </section>
      </Modal>
    </article>
  );
}

function ResponseHeader({
  modelName,
  statusLabel,
  scoreText,
  failed
}: {
  modelName: string;
  statusLabel: string;
  scoreText: string;
  failed: boolean;
}) {
  return (
    <header className="response-head">
      <div>
        <p className="panel-label">模型名称</p>
        <h3>{modelName}</h3>
      </div>
      <div className="response-status">
        <span className={failed ? "status-badge failed" : "status-badge"}>{statusLabel}</span>
        <strong className={failed ? "failed" : ""}>{scoreText}</strong>
      </div>
    </header>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  );
}

function normalizedScore(score: EvaluationScore): Required<EvaluationScore> {
  return {
    relevance: score.relevance || 0,
    completeness: score.completeness || 0,
    clarity: score.clarity || 0,
    format: score.format || 0,
    safety: score.safety || 0,
    final: score.final || 0,
    details: score.details || {},
    ruleFinal: score.ruleFinal ?? score.final ?? 0,
    judgeFinal: score.judgeFinal ?? null,
    baseFinal: score.baseFinal ?? score.final ?? 0,
    feedbackScore: score.feedbackScore ?? null,
    judgeComment: score.judgeComment ?? null,
    judgeDetails: score.judgeDetails || {}
  };
}

function formatCost(value: number): string {
  return value.toFixed(4).replace(/0+$/, "").replace(/\.$/, ".0");
}

// frontend/src/components/ModelResponseCard.vue
<template>
  <article class="response-card" :class="{ pending: response.pending }">
    <div class="response-head">
      <div>
        <p class="panel-label">模型名称</p>
        <h3>{{ response.modelName }}</h3>
      </div>
      <strong v-if="response.pending" class="pending-score">...</strong>
      <strong v-else :class="{ failed: response.status !== 'success' }">
        {{ response.status === "success" ? score.final : "失败" }}
      </strong>
    </div>

    <el-tag v-if="response.pending" type="warning" effect="plain">
      等待模型响应
    </el-tag>
    <el-tag v-else :type="response.status === 'success' ? 'success' : 'danger'" effect="plain">
      {{ response.status === "success" ? "调用成功" : "调用失败" }}
    </el-tag>

    <div v-if="response.pending" class="pending-answer" aria-label="模型响应等待中">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <MarkdownRenderer v-else :content="response.answer || ''" />

    <dl v-if="response.pending" class="metric-row pending-metrics">
      <div>
        <dt>耗时</dt>
        <dd>{{ elapsedSeconds }}s</dd>
      </div>
      <div>
        <dt>输出</dt>
        <dd>等待中</dd>
      </div>
      <div>
        <dt>成本</dt>
        <dd>待估算</dd>
      </div>
    </dl>
    <dl v-else class="metric-row">
      <div>
        <dt>耗时</dt>
        <dd>{{ response.latencyMs }}ms</dd>
      </div>
      <div>
        <dt>输出</dt>
        <dd>{{ response.outputTokens }}</dd>
      </div>
      <div>
        <dt>成本</dt>
        <dd>¥{{ response.estimatedCost }}</dd>
      </div>
    </dl>

    <div v-if="response.pending" class="pending-progress" aria-hidden="true">
      <i></i>
    </div>
    <div v-else class="score-bars">
      <ScoreBar label="相关性" :value="score.relevance" />
      <ScoreBar label="完整性" :value="score.completeness" />
      <ScoreBar label="清晰度" :value="score.clarity" />
      <ScoreBar label="格式" :value="score.format" />
      <ScoreBar label="安全性" :value="score.safety" />
    </div>

    <footer v-if="showActions && !response.pending" class="card-actions">
      <el-button
        :type="feedback.liked ? 'primary' : 'default'"
        :loading="feedbackSubmitting"
        @click="emitFeedback('like')"
      >
        点赞 {{ feedback.likeCount }}
      </el-button>
      <el-button
        :type="feedback.disliked ? 'danger' : 'default'"
        :loading="feedbackSubmitting"
        @click="emitFeedback('dislike')"
      >
        点踩 {{ feedback.dislikeCount }}
      </el-button>
      <el-button @click="detailVisible = true">详情</el-button>
    </footer>

    <el-dialog v-model="detailVisible" title="评分详情" width="680px" class="score-detail-dialog">
      <section class="score-detail">
        <div class="score-summary">
          <div>
            <p class="panel-label">最终分</p>
            <strong>{{ score.final }}</strong>
          </div>
          <dl>
            <div>
              <dt>规则分</dt>
              <dd>{{ score.ruleFinal ?? score.final }}</dd>
            </div>
            <div>
              <dt>LLM 评审</dt>
              <dd>{{ judgeScoreText }}</dd>
            </div>
            <div>
              <dt>耗时</dt>
              <dd>{{ response.latencyMs || 0 }}ms</dd>
            </div>
            <div>
              <dt>输出</dt>
              <dd>{{ response.outputTokens || 0 }}</dd>
            </div>
          </dl>
        </div>

        <article v-if="score.judgeComment" class="score-detail-item judge-detail-item">
          <header>
            <span>LLM 评审理由</span>
            <strong>{{ judgeScoreText }}</strong>
            <em>权重 40%</em>
          </header>
          <p>{{ score.judgeComment }}</p>
          <ul v-if="judgeDetailItems.length">
            <li v-for="detail in judgeDetailItems" :key="detail">{{ detail }}</li>
          </ul>
        </article>

        <article class="score-detail-item feedback-detail-item">
          <header>
            <span>用户反馈</span>
            <strong>{{ feedbackSummaryText }}</strong>
            <em>不计入当前评分</em>
          </header>
          <p>
            点赞 {{ feedback.likeCount }} 次，点踩 {{ feedback.dislikeCount }} 次；当前匿名用户反馈为{{ currentFeedbackText }}。
          </p>
        </article>

        <div class="score-detail-list">
          <article v-for="dimension in scoreDimensions" :key="dimension.key" class="score-detail-item">
            <header>
              <span>{{ dimension.label }}</span>
              <strong>{{ dimension.value }} / 10</strong>
              <em>权重 {{ dimension.weight }}</em>
            </header>
            <ul>
              <li v-for="detail in dimension.details" :key="detail">{{ detail }}</li>
            </ul>
          </article>
        </div>
      </section>
    </el-dialog>
  </article>
</template>

<script setup>
import { computed, ref } from "vue";

import MarkdownRenderer from "./MarkdownRenderer.vue";
import ScoreBar from "./ScoreBar.vue";

const props = defineProps({
  response: {
    type: Object,
    required: true
  },
  elapsedSeconds: {
    type: Number,
    default: 0
  },
  showActions: {
    type: Boolean,
    default: false
  },
  feedbackSubmitting: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(["feedback"]);

const score = computed(() => {
  return props.response.score || {
    relevance: 0,
    completeness: 0,
    clarity: 0,
    format: 0,
    safety: 0,
    final: 0,
    ruleFinal: 0,
    judgeFinal: null,
    judgeComment: null,
    judgeDetails: {}
  };
});

const detailVisible = ref(false);

const feedback = computed(() => {
  return props.response.feedback || {
    liked: false,
    disliked: false,
    likeCount: 0,
    dislikeCount: 0
  };
});

const feedbackSummaryText = computed(() => {
  if (feedback.value.liked) {
    return "已点赞";
  }
  if (feedback.value.disliked) {
    return "已点踩";
  }
  return "未反馈";
});

const currentFeedbackText = computed(() => {
  if (feedback.value.liked) {
    return "点赞";
  }
  if (feedback.value.disliked) {
    return "点踩";
  }
  return "未选择";
});

const scoreDimensions = computed(() => {
  const details = score.value.details || {};
  return [
    makeScoreDimension("relevance", "相关性", score.value.relevance, "20%", details),
    makeScoreDimension("completeness", "完整性", score.value.completeness, "30%", details),
    makeScoreDimension("clarity", "清晰度", score.value.clarity, "20%", details),
    makeScoreDimension("format", "格式", score.value.format, "15%", details),
    makeScoreDimension("safety", "安全性", score.value.safety, "15%", details)
  ];
});

const judgeScoreText = computed(() => {
  return score.value.judgeFinal === null || score.value.judgeFinal === undefined
    ? "未启用"
    : `${score.value.judgeFinal} / 10`;
});

const judgeDetailItems = computed(() => {
  const details = score.value.judgeDetails || {};
  return Object.entries(details).flatMap(([label, items]) => {
    if (!Array.isArray(items)) {
      return [];
    }
    return items.map((item) => `${judgeDetailLabel(label)}：${item}`);
  });
});

function makeScoreDimension(key, label, value, weight, details) {
  return {
    key,
    label,
    value: value || 0,
    weight,
    details: details[key]?.length ? details[key] : ["暂无命中项明细"]
  };
}

function judgeDetailLabel(key) {
  const labels = {
    strengths: "优点",
    weaknesses: "缺点",
    recommendation: "建议",
    dimensionScores: "维度分"
  };
  return labels[key] || key;
}

function emitFeedback(feedbackType) {
  emit("feedback", {
    responseId: props.response.id,
    feedbackType
  });
}
</script>
