// frontend/src/components/ScoreBar.tsx
interface ScoreBarProps {
  label: string;
  value: number;
}

export function ScoreBar({ label, value }: ScoreBarProps) {
  const normalizedValue = Math.max(0, Math.min(value * 10, 100));
  return (
    <div className="score-bar">
      <span>{label}</span>
      <div className="bar-track">
        <i style={{ width: `${normalizedValue}%` }} />
      </div>
      <strong>{formatScore(value)}</strong>
    </div>
  );
}

export function formatScore(value: number | null | undefined): string {
  if (value === null || value === undefined) {
    return "-";
  }
  return Number.isInteger(value) ? String(value) : value.toFixed(2);
}

// frontend/src/components/ScoreBar.vue
<template>
  <div class="score-bar">
    <span>{{ label }}</span>
    <div class="bar-track">
      <i :style="{ width: `${normalizedValue}%` }"></i>
    </div>
    <strong>{{ value }}</strong>
  </div>
</template>

<script setup>
import { computed } from "vue";

const props = defineProps({
  label: {
    type: String,
    required: true
  },
  value: {
    type: Number,
    required: true
  }
});

const normalizedValue = computed(() => Math.max(0, Math.min(props.value * 10, 100)));
</script>
