// frontend/src/components/MarkdownRenderer.tsx
import DOMPurify from "dompurify";
import MarkdownIt from "markdown-it";

import { parseThinkContent } from "../features/evaluation/content";

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true
});

const defaultLinkOpen =
  markdown.renderer.rules.link_open ||
  ((tokens, index, options, _environment, self) => self.renderToken(tokens, index, options));

markdown.renderer.rules.link_open = (tokens, index, options, env, self) => {
  const token = tokens[index];
  const targetIndex = token.attrIndex("target");
  const relIndex = token.attrIndex("rel");

  if (targetIndex < 0) {
    token.attrPush(["target", "_blank"]);
  } else if (token.attrs) {
    token.attrs[targetIndex][1] = "_blank";
  }

  if (relIndex < 0) {
    token.attrPush(["rel", "noopener noreferrer"]);
  } else if (token.attrs) {
    token.attrs[relIndex][1] = "noopener noreferrer";
  }

  return defaultLinkOpen(tokens, index, options, env, self);
};

interface MarkdownRendererProps {
  content: string;
}

export function MarkdownRenderer({ content }: MarkdownRendererProps) {
  const parsedContent = parseThinkContent(content);
  const answerHtml = sanitizeMarkdown(parsedContent.answer || "暂无回答内容");
  const thoughtHtml = parsedContent.thought ? sanitizeMarkdown(parsedContent.thought) : "";

  return (
    <div className="answer-text">
      {thoughtHtml ? (
        <details className="think-panel">
          <summary>思考过程</summary>
          <div className="markdown-body think-content" dangerouslySetInnerHTML={{ __html: thoughtHtml }} />
        </details>
      ) : null}
      <div className="markdown-body" dangerouslySetInnerHTML={{ __html: answerHtml }} />
    </div>
  );
}

function sanitizeMarkdown(source: string): string {
  return DOMPurify.sanitize(markdown.render(source), {
    ADD_ATTR: ["target"]
  });
}

// vue-frontend/src/components/MarkdownRenderer.vue
<template>
  <div class="answer-text">
    <details v-if="renderedThoughtHtml" class="think-panel">
      <summary>思考过程</summary>
      <div class="markdown-body think-content" v-html="renderedThoughtHtml"></div>
    </details>
    <div class="markdown-body" v-html="renderedAnswerHtml"></div>
  </div>
</template>

<script setup>
import DOMPurify from "dompurify";
import MarkdownIt from "markdown-it";
import { computed } from "vue";

const props = defineProps({
  content: {
    type: String,
    default: ""
  }
});

const markdown = new MarkdownIt({
  html: false,
  linkify: true,
  breaks: true
});

const defaultLinkOpen =
  markdown.renderer.rules.link_open ||
  ((tokens, index, options, env, self) => self.renderToken(tokens, index, options));

markdown.renderer.rules.link_open = (tokens, index, options, env, self) => {
  const token = tokens[index];
  const targetIndex = token.attrIndex("target");
  const relIndex = token.attrIndex("rel");

  if (targetIndex < 0) {
    token.attrPush(["target", "_blank"]);
  } else {
    token.attrs[targetIndex][1] = "_blank";
  }

  if (relIndex < 0) {
    token.attrPush(["rel", "noopener noreferrer"]);
  } else {
    token.attrs[relIndex][1] = "noopener noreferrer";
  }

  return defaultLinkOpen(tokens, index, options, env, self);
};

function sanitizeMarkdown(source) {
  return DOMPurify.sanitize(markdown.render(source), {
    ADD_ATTR: ["target"]
  });
}

function parseThinkContent(content) {
  const source = content || "";
  const thoughts = [];
  let answer = source;

  answer = answer.replace(/<think>([\s\S]*?)<\/think>/gi, (_, thought) => {
    thoughts.push(thought.trim());
    return "";
  });

  const unmatchedStart = answer.search(/<think>/i);
  if (unmatchedStart >= 0) {
    const thought = answer.slice(unmatchedStart).replace(/<think>/i, "").trim();
    thoughts.push(thought);
    answer = answer.slice(0, unmatchedStart);
  }

  return {
    answer: answer.trim(),
    thought: thoughts.filter(Boolean).join("\n\n---\n\n")
  };
}

const parsedContent = computed(() => parseThinkContent(props.content));

const renderedThoughtHtml = computed(() => {
  if (!parsedContent.value.thought) {
    return "";
  }
  return sanitizeMarkdown(parsedContent.value.thought);
});

const renderedAnswerHtml = computed(() => {
  const source = parsedContent.value.answer || "暂无回答内容";
  return sanitizeMarkdown(source);
});
</script>
